# Generated by Django 5.1.1 on 2024-10-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='CVV',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
    ]
