# Generated by Django 5.1.1 on 2024-11-08 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='CVV',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Checked_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=64)),
                ('city', models.CharField(default='', max_length=64)),
                ('lastName', models.CharField(default='', max_length=64)),
                ('firstName', models.CharField(default='', max_length=64)),
                ('postcode', models.CharField(default='', max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Checked_card', to='api.card')),
            ],
        ),
    ]
