# Generated by Django 5.1.1 on 2024-09-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_country_alter_card_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bank',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.IntegerField(default=8.0),
        ),
        migrations.AlterField(
            model_name='card',
            name='BIN',
            field=models.IntegerField(default=8.0),
        ),
    ]
