# Generated by Django 5.1.1 on 2024-11-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_checked_card_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Base',
        ),
        migrations.AlterField(
            model_name='card',
            name='Company',
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveField(
            model_name='card',
            name='BIN',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ZIP_code',
        ),
        migrations.RemoveField(
            model_name='card',
            name='bank',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
