# Generated by Django 5.1.1 on 2024-11-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_city_card_address_rename_state_card_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Company',
        ),
    ]
